### ISSUE TITLE
Error while complie PahoMQTT

### ISSUE THREAD

**Issue by rudenko-ks** [br-automation-com/paho.mqtt.c-ar#10] opened 2021-04-12 14:04 UTC
Hello.
I am having difficulties compiling the PahoMQTT library (PahoMQTT \ 1.3.8-rev04 \ PahoMQTT \ V4.73.0).
It seems that I did everything according to the instructions, but the following errors occur:
![0](https://user-images.githubusercontent.com/3808020/114406358-26a79b80-9bb0-11eb-9f01-bebce4b18888.PNG)

Settings:
![1](https://user-images.githubusercontent.com/3808020/114406554-4e96ff00-9bb0-11eb-83e0-338941ff0c08.PNG)

Library removed according to instructions in top Readme.md
_"Further, and very important is that you cannot assign the library to a CPU, as it contains no .br file. Therefore remove it from your CPU configuration if it showed up there, you link directly to the archive file instead."_ 
And also the following settings are specified in the Linker tab for the task 
![2](https://user-images.githubusercontent.com/3808020/114406869-8dc55000-9bb0-11eb-9dea-7ef582b7b1d1.PNG)

Library version: PahoMQTT\1.3.8-rev04\V4.73.0
![3](https://user-images.githubusercontent.com/3808020/114407288-eac10600-9bb0-11eb-93b6-f830bc2a1d38.PNG)

AS 4.8.4.50
Hardware: 5PP520.0702-00

**Comment by JobFranken** [comment] 2021-04-12 14:26
You didn't deploy the PahoMQTT library. (  Its not shown in the Library objects at the Software )
The first Warning at line 5 reports this.

**Comment by rudenko-ks** [comment] 2021-04-12 14:41
I didn't quite understand you. The main page in Readme.md says:
![image](https://user-images.githubusercontent.com/3808020/114412721-05e24480-9bb6-11eb-8e1b-c5fc87aaf77f.png)


Okay. I added the library and made it static. The error has not disappeared: 
![1](https://user-images.githubusercontent.com/3808020/114412844-27dbc700-9bb6-11eb-8196-f70957bb99fd.PNG)

**Comment by JobFranken** [comment] 2021-04-12 15:16
Oké , I tried to do the steps myself and I found that the "PahoMQTT.h" was missing. How did you fix that ? 
If I take the file from a older version (PahoMQTT\1.3.5-rev01\PahoMQTT\V3.10.0\SG4\include) it all compiles without any issue. 

![image](https://user-images.githubusercontent.com/33413577/114418417-c6662900-9bb2-11eb-9cbf-d72731a90f14.png)

**Comment by rudenko-ks** [comment] 2021-04-12 19:25
I tried to add "PahoMQTT.h" to "PahoMQTT \ 1.3.8-rev04 \ PahoMQTT \ V4.73.0 \ SG4 \ include" and re-add this version of the library to the project and compile it. But this was unsuccessful. Despite the fact that the path to the headers was specified in the project properties.

After repeating your steps and adding the file to the project, it compiled successfully.

As far as I understand, in the next commit you will fix this error?

**Comment by rudenko-ks** [comment] 2021-04-12 19:35
> You didn't deploy the PahoMQTT library. ( Its not shown in the Library objects at the Software )
> The first Warning at line 5 reports this.

I just tried to remove it from "Library objects" now - the project was compiled successfully and the program works fine.
So, I still do not understand whether it is necessary to remove the library from "Library objects" according to the information on the main page?
Or is it still necessary to leave it and set it as static?

![](https://user-images.githubusercontent.com/3808020/114412721-05e24480-9bb6-11eb-8e1b-c5fc87aaf77f.png)

**Comment by JobFranken** [comment] 2021-04-13 09:13
The documentation points to manual linking all the objects,  When adding it to the software AS maybe wants to do it by itself again and this could give some other behavior.. 

That the file is missing in the later build should be fixed.

**Comment by patricthysell** [comment] 2021-09-06 13:44
Hi, I checked the problem, and It seemed strange, since were just reaching through the parameters to the paho library, and in my samples Ive always milliseconds aswell. 

Think the problem is here (inside the paho source library) - we didn't modify these sources

https://github.com/br-automation-com/paho.mqtt.c-ar-dev/blob/master/src/MQTTAsync.c - line 2136

There the elapsed milliseconds are compared with the timeout * 1000, therefore timeout needs to be set in seconds.

![image](https://user-images.githubusercontent.com/24934017/132225432-0b707db8-6208-4bb3-966d-701ba6dcc8ff.png)

I cannot find the same line in the current pahomqtt master branch, the sources are completely restructured, but probably theres a bugfix for it. 

If theres a bugfix in a later version, we can create a new ported version. 

cheers

**Comment by patricthysell** [comment] 2021-09-06 14:12
update paho_mqtt_c_ar_project.xml with AdditionalHeaderFile for PahoMQTT

**Closed** 2023-05-03 14:45 UTC
Labels: bug
